// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// pval_correct.cpp
cpp11::writable::doubles pval_correct_cpp(cpp11::doubles pval_matrix);
extern "C" SEXP _fdatest_pval_correct_cpp(SEXP pval_matrix) {
  BEGIN_CPP11
    return cpp11::as_sexp(pval_correct_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(pval_matrix)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_fdatest_pval_correct_cpp", (DL_FUNC) &_fdatest_pval_correct_cpp, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_fdatest(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
